# permissions for end users to edit globalinclusterippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalinclusterippool-editor-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalinclusterippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalinclusterippools/status
  verbs:
  - get
