# permissions for end users to view globalinclusterippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalinclusterippool-viewer-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalinclusterippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalinclusterippools/status
  verbs:
  - get
