# permissions for end users to edit inclusterippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inclusterippool-editor-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - inclusterippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - inclusterippools/status
  verbs:
  - get
