# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: ""
  name: inclusterippools.ipam.cluster.x-k8s.io
