apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  labels:
    app.kubernetes.io/name: inclusterippool
    app.kubernetes.io/instance: inclusterippool-sample
    app.kubernetes.io/part-of: cluster-api-ipam-provider-in-cluster
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-ipam-provider-in-cluster
  name: inclusterippool-sample
spec:
  addresses:
  - 10.0.0.2-10.0.0.254
  prefix: 24
  gateway: 10.0.0.1
  excludedAddresses:
  - 10.0.0.3-10.0.1.6
  - 10.0.0.10
  - 10.0.0.192/26
